url: http://chubbssolutions.github.io
baseurl:

# Site settings
title: Chubbs Solutions
email: admin@chubbs.solutions
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Nate-0
  pic: nate
  position: CEO
#  social:
   # - title: twitter
   #   url: #
   # - title: facebook
   #   url: #
   # - title: stack-overflow
   #   url: #

- name: Damon-0
  pic: damon
  position: Talent 
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: linkedin
#      url: #

- name: Mike-arita
  pic: mike
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/chubbssolutions
 ## - title: facebook
  ##  url:
 ## - title: stack-overflow
  ##  url: http://stackoverflow.com/questions/tagged/jekyll
##  - title: bitbucket 
 ##   url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/chubbsolutions

# Postal address (add as many lines as necessary)
address:
#  - line: 3481 Melrose Place
  - line: Fort Wayne, IN

# Build settings
markdown: kramdown
permalink: pretty
